version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:RELEASE.2025-01-01T00-00-00Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"
  web:
    build: .
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=your_bot_token
      - RENDER_EXTERNAL_URL=http://localhost:10000
      - PORT=10000
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - S3_BUCKET=local-bucket
      - S3_REGION=us-east-1
    depends_on:
      - redis
      - minio
    command: python bot/main.py
